language: node_js
node_js:
  - "7"
env:
  matrix:
    - TEST_SUITE=test
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: TEST_SUITE=coveralls
    - os: linux
      node_js: "7"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
